config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :blogs do
     resources :comments do
      resources :replies
    end
  end
  #root  'comments#index'
  # resources :comments, only: [:index, :create]
  # get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  
  
 root 'blogs#index'
  get '/my_blogs' =>"blogs#my_blogs"

  get 'blog/profile' => 'blogs#profile'
  get "/user/addfriend" => "blogs#friend"
  get "/user/acc" => "blogs#accept_friend"
  get "/user/de" => "blogs#delete_friend"

  

  resources :blogs, only: [] do
    member do
     get "like", to: "blogs#upvote"
     get "dislike", to: "blogs#downvote"
    end
  end
  resources :blogs, only: []  do 
    member do 
      get "follow", to: "blogs#follow" 
      get "unfollow", to: "blogs#unfollow" 
    end 
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	acts_as_followable
	 mount_uploader :image, AvatarUploader
	 acts_as_votable
     has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
 #acts_as_tree order: 'created_at DESC'
  belongs_to :blog
  has_many :replies
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord

	belongs_to :bbb, foreign_key: 'sender', class_name: 'User'
	belongs_to :ccc, foreign_key: 'receiver', class_name: 'User'
	# belongs_to :friend, foreign_key: 'sender', class_name: 'User'
	# belongs_to :user, foreign_key: 'receiver', class_name: 'User'
	# belongs_to :friend, :class_name => "User"

end

app/models/reply.rb
class Reply < ApplicationRecord
	belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
	acts_as_followable
    acts_as_follower
    has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         mount_uploader :avatar, AvatarUploader
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!
	def index
  @blogs=Blog.all

	end

	def new
		@blog=Blog.new
	end

	def create
		@blog=Blog.new(blog_params)
		@blog.user_id = current_user.id
		@blog.save
		redirect_to @blog
	end
         

	def show
		@blog=Blog.find(params[:id])
  end
      
  def friend

    if Friendship.where(sender: current_user.id,receiver: params[:id], accept: false).first.present?
      flash[:notice] = "you have already sent the friend  request to this user"
        
      elsif Friendship.where(sender: current_user.id,receiver: params[:id], accept: true).first.present?
       
      flash[:notice] = "You are already friend of this user"  
      else

      Friendship.create(sender: current_user.id,receiver: params[:id], accept: false )
      flash[:notice] = "freind request sent"  
    end
  
    redirect_to blog_profile_path(id: current_user.id)
  end

  def accept_friend

   @abc=Friendship.where(receiver: params[:re] ,sender: params[:se]).first
   @abc.update(accept: true)
    flash[:notice] = "Now you are friend with #{User.where(id: params[:se]).first.email}"
    redirect_to blog_profile_path(id: current_user.id)
  end
 def delete_friend

   @abc=Friendship.where(receiver: params[:re] ,sender: params[:se]).first
   @abc.destroy
   flash[:notice] = "request deleted"
   redirect_to blog_profile_path(id: current_user.id)
  end
  # def notification

  #  @likenotifications= Notification.where(recipient_id: current_user.id,notifiable_for: "like")
  #   @dislikenotifications= Notification.where(recipient_id: current_user.id,notifiable_for: "dislike")
    
  # end

  # GET /users/:id.:format
  def profile
    
   if Friendship.where(receiver: current_user.id).first.present?
      @friend_request=Friendship.where(receiver: current_user.id)
    end 

    @user = User.all.where.not(id: current_user)
    
  
    if Friendship.where(receiver: current_user.id).first.present? || Friendship.where(sender: current_user.id).first.present?

      @friends = Friendship.where(receiver: current_user.id)
    
      @friends1 = Friendship.where(sender: current_user.id)
    end
  end



  def upvote
   @blog = Blog.find(params[:id])
   @blog.upvote_by current_user
   
    redirect_to :back 
  end

  def downvote
   @blog = Blog.find(params[:id])
   @blog.downvote_by current_user
   
    redirect_to :back 
  end

  def follow

   # if Follow.where(follower_id: params[:id], follower_type: "User",followable_id: params[:id],followable_type: "ApplicationRecord").first.present? 
    @follow= Follow.create(follower_id: params[:id], followable_id: current_user.id,follower_type: "User",followable_type: "ApplicationRecord") 
    # end
    redirect_to :back 
  end 

  def unfollow 
   
   #if Follow.where(follower_id: params[:id], follower_type: "User").first.present?
    @unfoll = Follow.where(follower_id: params[:id], follower_type: "User",followable_id: current_user.id).first
    
    @unfollow = @unfoll.destroy
    #end
  
    redirect_to :back 
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
 
    if @blog.update(blog_params)
      redirect_to @blog
      else
      render 'edit'
    end
  end 

  def my_blog
    @blogs= Blog.where(:user_id => current_user.id)
  end



  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
 
    redirect_to blogs_path
  end
 

  private
  def blog_params
    params.require(:blog).permit(:title, :description, :image)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # def create
	   #  @blog = Blog.find(params[:blog_id])
	   #  @comment = @blog.comments.create(comment_params)
	   #  redirect_to blog_path(@blog)
    # end
  def index

     @comments = Comment.all

    # Comment.hash_tree(limit_depth: 2)
  end

  def new
   @comment = Comment.new(parent_id: params[:parent_id])
  end

  def create

    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)
     else
      @comment = Comment.new(comment_params)
    end

    if @comment.save
      flash[:success] = 'Your comment was successfully added!'
      redirect_to root_url
       else
      render 'new'
    end
 end
    # def destroy
	   #  @blog = Blog.find(params[:blog_id])
	   #  @comment = @blog.comments.find(params[:id])
	   #  @comment.destroy
	   #  redirect_to blog_path(@blog)
    # end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body,:parent_id)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	before_action do
    @comment = Comment.find(params[:comment_id])
  end

  def index
    @replies = @comment.replies
    @reply = @comment.replies.new
  end

  def new
    @reply = @comment.replies.new
  end

  def create

    @reply =  Reply.new(:body=>params[:reply][:body],:comment_id=>params[:reply][:comment_id])
    @reply.save
    flash[:notice]= "replies created"
    redirect_to "/blogs/#{params[:blog_id]}"
    #redirect somewhere
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	 def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
          (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") : nil)
    end.join.html_safe
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/bloglike.js.erb
$(function() { 
  $('.blog-up-<%=@blog.id%>').text("<%= @blog.get_upvotes.size %>");
  $('.blog-down-<%=@blog.id%>').text("<%= @blog.get_downvotes.size %>");
});

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>
 
<<%= form_for @blog do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
 
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', blog_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
     <!-- <th>Image</th> -->
      <th colspan="3"></th>
  </tr>
 
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.description %></td>
      <!-- <td><%=image_tag blog.image %></td> -->
       <td><%= link_to like_blog_path(blog),:class=> "btn btn-default" do %>
                           <span class="glyphicon glyphicon-thumbs-up blog-up-<%=blog.id%>" style='width: 50px' >
                           <%= blog.get_upvotes.count %>
                           <% end %>
                        </td>
                        </span>
                        <td><%= link_to  dislike_blog_path(blog), :class=> "btn btn-default" do %>
                           <span class="glyphicon glyphicon-thumbs-down blog-down-<%=blog.id%>" style='width: 50px'>
                           <%= blog.get_downvotes.count %>
                           <% end %>
                                
                                <%#byebug%>
                            <%#if current_user != blog%> 
                           <%#if current_user.following?(blog)%>
                              
                               
                              <% if (params[:follower_id] == params[:id]) && (params[:followable_id] == current_user.id)%>
                              <%# if  (params[:follower_id] == params[:id]) && (params[:follower_type] == "user")%>
                               
                             <%= link_to(unfollow_blog_path(blog), :class => "btn btn-primary") do %> 
                                 <span class="icon-remove"></span> 
                                 Un-Follow 

                               <% end %> 
                              <%else%> 
                          <%= link_to(follow_blog_path(blog), :class => 'btn btn-primary') do %> 
                                  <span class="icon-ok icon-white"></span> 
                                  Follow 
                                  <%end%> 
                          <%end%> 
                          <%#end%>


      <td><%= link_to 'Show', blog_path(blog) %></td>
      <%# if current_user.id == blog.user_id %>

      <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
      <td><%= link_to 'Destroy', blog_path(blog),method: :delete,
      data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <%# end %>
  <% end %>
</table>
<%= link_to 'New blog', new_blog_path %>

app/views/blogs/new.html.erb
 <%= form_for :blog,url:blogs_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
 
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', blogs_path %>

app/views/blogs/profile.html.erb
 
 <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo1">your friends</button> <br>
<div class="container">
   <div id="demo1" class="collapse">
      <% if @friends !=nil %>
      <%  @friends.each do |friend| %>
      <%= User.where(id: friend.sender).first.email %>
      <%#= user.collect(&:email)%>
      <% end %>
      <% end %>
      <%if @friends1 !=nil%>
      <%  @friends1.each do |friend| %>
      <td><%= User.where(id: friend.receiver).first.email %></td>
      <%#= use.collect(&:email)%>
      <% end %>
      <% end %>
   </div>
</div>
<br><button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Add a friend</button>  
<div class="container">
   <div id="demo" class="collapse">
      <%#byebug%>
      <% @user.each do |user| %>
      <p>
         <%= user.email %>
         <%= link_to "Add Friend", user_addfriend_path(id: user.id) %>
      </p>
      <% end %>
      <%if @friend_request !=nil%>
      <%  @friend_request.each do |frr| %>
      <p>
         <%unless frr.accept==true&&frr !=nil%>
         <%@userr=User.where(id: frr.sender).first%>
         <%= "u have a friend request from #{@userr.email }" %>
         <%= link_to "accept", user_acc_path(re: current_user.id,se: @userr.id) %>
         <%= link_to "delete", user_de_path(re: current_user.id,se: @userr.id) %>
         <%end%>
      </p>
      <% end %>
      <% end %>
   </div>
</div>
<!DOCTYPE html>
<html lang="en">
   <head>
      <title>Profile </title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="css/style.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   </head>
   <body style="padding-top:50px;">
      <div class="container">
         <center>
            <!--  <a href=""><img src="images/Generic-profile-image.png" class="img-circle" alt="Cinque Terre" ></a> -->
         </center>
      </div>
      <br/><br/><br/><br/><br/>
      <div class="continer my-continer padd2">
         <p >About</p>
         <!-- <div class="well well-sm  ">
            </div> --><br/><br/><br/><br/><br/><br/><br/><br/><br/>
         <div class="btn-group">
            <p>Intrest</p>
            <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Design</button>
            <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Art</button>
            <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Graphics</button>
            <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Music</button>
            <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Drama</button>
         </div>
         <br/><br/><br/>
         <div class="container">
            <div class="col-md-10">
               <center><button style="padding:5px 60px;" type="button" class="btn">Next</button></center>
            </div>
            <div class="col-md-2">
               <p class="alinright"> <a href=""></a></p>
            </div>
         </div>
      </div>
   </body>
</html>

app/views/blogs/profile/show.html.erb
 <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo1">your friends</button> <br>
<div class="container">
<div id="demo1" class="collapse">
      <% if @friends !=nil %>
          <%  @friends.each do |friend| %>
           <%= User.where(id: friend.sender).first.email %>
          <% end %>
      <% end %>

      <%if @friends1 !=nil%>
            <%  @friends1.each do |friend| %>
             <%= User.where(id: friend.receiver).first.email %>
            <% end %>
      <% end %>
</div>
</div>

  <br><button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Add a friend</button>  
<div class="container">
<div id="demo" class="collapse">
  
<% @user.each do |user| %>
  <p>
  
    <%= user.email %>
    <%= link_to "Add Friend", user_addfriend_path(id: blog.id) %>
  </p>
 
<% end %>
<%if @friend_request !=nil%>

<%  @friend_request.each do |frr| %>
  <p>
     <%unless frr.accept==true&&frr !=nil%>
     <%@userr=blog.where(id: frr.sender).first%>
    <%= "u have a friend request from #{@userr.email }" %>
    <%= link_to "accept", user_acc_path(re: current_user.id,se: @userr.id) %>
    
  <%= link_to "delete", user_de_path(re: current_user.id,se: @userr.id) %>
    <%end%>
  </p>
 
  
<% end %>
<% end %>

 </div>
</div>





<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Profile </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body style="padding-top:50px;">
    <div class="container">
      <center>
        <a href=""><img src="images/Generic-profile-image.png" class="img-circle" alt="Cinque Terre" ></a>
      </center>
    </div><br/><br/><br/><br/><br/>
    <div class="continer my-continer padd2">
      <p >About</p>
      <!-- <div class="well well-sm  ">
       

      </div> --><br/><br/><br/><br/><br/><br/><br/><br/><br/>
      <div class="btn-group">
        <p>Intrest</p>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Design</button>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Art</button>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Graphics</button>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Music</button>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Drama</button>
      </div>
      <br/><br/><br/>
      <div class="container">
        <div class="col-md-10">
          <center><button style="padding:5px 60px;" type="button" class="btn">Next</button></center>
        </div>
        <div class="col-md-2">
          <p class="alinright"> <a href=""></a></p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/blogs/show.html.erb
 <div class="col-md-6">
 <p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>
<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image %>
</p>
<%#= render @comments %>
<%#= comments_tree_for @comments %>
 </div>
<div class="col-md-6">
  <h2>Comments</h2>
<%= render @blog.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 </div>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<br><br><br><br><br><br>

app/views/blogs/upvote.js.erb
$('.blog-up-<%=@blog.id%>').text("<%= @blog.get_upvotes.size %>");

app/views/comments/_comment.html.erb
 <p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.blog, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

<h2> reply a comment</h2>
<% @replies= Reply.where(:comment_id=> comment.id)
%>

<% @replies.each do |reply|%>
  <p><strong>Reply:</strong><%=reply.body%></p>
<%end%>
<%= render 'replies/form', :comment=>comment %>

app/views/comments/_form.html.erb
<%= form_for([@blog, @blog.comments.build]) do |f| %>
 <%#= form_for(@comment) do |f| %>

  <%#= f.hidden_field :parent_id %>

  <p>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
  

app/views/comments/index.html.erb
<!-- <div class="jumbotron">
  <div class="container">
    <h1>Join the discussion</h1>
    <p>Click the button below to start a new thread:</p>
    <p>
      <%= link_to 'Add new topic', new_comment_path, class: 'btn btn-primary btn-lg' %>
    </p>
    <div class=".replies">
    <%= comments_tree_for @comments %>
    	
    </div>

  </div>
</div>

<%= render @comments %>
 -->

app/views/comments/new.html.erb
<h1>New comment</h1>

<% if @comment.parent %>
  <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <body>


  <div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    
    <%=link_to "my Blogs","/my_blogs" %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>
    <%= yield %>
  </body>
</html>

app/views/replies/_form.html.erb
<%= form_for :reply, url: "/blogs/#{@blog.id}/comments/#{comment.id}/replies" do |f| %>
   <%= f.hidden_field :comment_id,  :value=> comment.id %>
   <%= f.text_field :body %><br/><br/>
   <%= f.submit %>
<% end %>

app/views/replies/_reply.html.erb
<p>
<%= comment.body %>
<%= render comment.replies if comment.replies.any? %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome ruby on rails!</h1>